SET search_path = SHOESTORE;

DROP SCHEMA IF EXISTS SHOESTORE CASCADE;
CREATE SCHEMA SHOESTORE;

CREATE DOMAIN SHOESTORE.sexType AS CHAR
	CHECK (VALUE IN ('M', 'F','U'));

CREATE TABLE IF NOT EXISTS Client ( 

	CID INTEGER NOT NULL,
	Fname VARCHAR(30) NOT NULL,
	Lname VARCHAR(30) NOT NULL,
	Email VARCHAR(30) UNIQUE NOT NULL,
	Gender SEXTYPE DEFAULT 'U',
	Dob DATE NOT NULL,
	PRIMARY KEY (CID)
);

CREATE TABLE IF NOT EXISTS Category ( 

	CatID INTEGER NOT NULL,
	nom VARCHAR(15) NOT NULL,
	isMen BOOLEAN DEFAULT TRUE,
	Image VARCHAR(50) NOT NULL,
	PRIMARY KEY (CatID)
);

CREATE TABLE IF NOT EXISTS Shoes ( 

	SID INTEGER NOT NULL,
	Name VARCHAR(30) NOT NULL,
	Price INTEGER NOT NULL,
	Image VARCHAR(50) NOT NULL,
	CatID INTEGER NOT NULL,
	PRIMARY KEY (SID),
	FOREIGN KEY (CatID) REFERENCES Category(CatID)
);

CREATE TABLE IF NOT EXISTS Orders ( 

	Dor DATE NOT NULL,
	Hour TIME NOT NULL,
	SID INTEGER NOT NULL,
	CID INTEGER NOT NULL,
	quantity INTEGER NOT NULL,
	Image VARCHAR(50) NOT NULL,
	PRIMARY KEY (SID,CID,Dor,Hour),
	FOREIGN KEY (CID) REFERENCES Client(CID), 
	FOREIGN KEY (SID) REFERENCES Shoes(SID)
);

CREATE TABLE IF NOT EXISTS Sizes ( 

	SizeID INTEGER NOT NULL,
	Size NUMERIC(2,1) NOT NULL,
	PRIMARY KEY (SizeID)
);

CREATE TABLE IF NOT EXISTS Colors ( 

	ColorID INTEGER NOT NULL,
	Color VARCHAR(10) NOT NULL,
	PRIMARY KEY (ColorID)
);

CREATE TABLE IF NOT EXISTS AvailableShoes ( 

	SizeID INTEGER NOT NULL,
	ColorID INTEGER NOT NULL,
	SID INTEGER NOT NULL,
	Quantity INTEGER NOT NULL,
	PRIMARY KEY (SizeID,ColorID,SID),
	FOREIGN KEY (SID) REFERENCES Shoes(SID), 
	FOREIGN KEY (SizeID) REFERENCES Sizes(SizeID),
	FOREIGN KEY (ColorID) REFERENCES Colors(ColorID)
);

